// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
namespace PVPSdk
{
    /// <summary>
    /// 支付验证
    /// </summary>
	public class Payment
	{
        /// <summary>
        /// google play 支付见证
        /// </summary>
        /// <param name="inAppPurchaseData">In app purchase data.</param>
        /// <param name="inAppDataSignature">In app data signature.</param>
		public static void CheckGooglePlayBilling(string inAppPurchaseData, string inAppDataSignature){
			PVP.ICM.gameServerClient.OpPaymentCheckGooglePlayBilling(inAppPurchaseData, inAppDataSignature);
		}
	}
}

