// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
namespace PVPSdk.PVP
{
    /// <summary>
    /// 挑战信息
    /// </summary>
	public class SocialChallengeInfo
	{
        public string key{
            get;
            private set;
        }

        public Int32 lobbyId {
            get;
            private set;
        }

        public UInt64 challengePlayerId{
            get;
            private set;
        }

        public string challengeName {
            get;
            private set;
        }

        public string challengeAvatar{
            get;
            private set;
        }

		internal SocialChallengeInfo (PVPProtobuf.Social_ReceivedChallenge_Broadcast b)
		{
            this.key = b.key;
            this.lobbyId = b.lobby_id;
            this.challengePlayerId = b.challenge_player_id;
            this.challengeName = b.challenge_name;
            this.challengeAvatar = b.challenge_avatar;
		}
	}
}

