//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: PVPClient.proto
namespace PVPClient
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AutoLoginInfo")]
  internal partial class AutoLoginInfo : global::ProtoBuf.IExtensible
  {
    internal AutoLoginInfo() {}
    
    private string _facebook_fb_uid = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"facebook_fb_uid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    internal string facebook_fb_uid
    {
      get { return _facebook_fb_uid; }
      set { _facebook_fb_uid = value; }
    }
    private bool _auto_login = (bool)false;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"auto_login", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue((bool)false)]
    internal bool auto_login
    {
      get { return _auto_login; }
      set { _auto_login = value; }
    }
    private int _login_type = (int)0;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"login_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    internal int login_type
    {
      get { return _login_type; }
      set { _login_type = value; }
    }
    private ulong _guest_player_id = (ulong)0;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"guest_player_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((ulong)0)]
    internal ulong guest_player_id
    {
      get { return _guest_player_id; }
      set { _guest_player_id = value; }
    }
    private ulong _facebook_player_id = (ulong)0;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"facebook_player_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((ulong)0)]
    internal ulong facebook_player_id
    {
      get { return _facebook_player_id; }
      set { _facebook_player_id = value; }
    }
    private long _facebook_expires = (long)0;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"facebook_expires", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((long)0)]
    internal long facebook_expires
    {
      get { return _facebook_expires; }
      set { _facebook_expires = value; }
    }
    private string _facebook_access_token = "";
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"facebook_access_token", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    internal string facebook_access_token
    {
      get { return _facebook_access_token; }
      set { _facebook_access_token = value; }
    }
    private string _guest_access_token = "";
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"guest_access_token", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    internal string guest_access_token
    {
      get { return _guest_access_token; }
      set { _guest_access_token = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}