//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: PVPProtobuf_Token.proto
namespace PVPProtobuf_Token
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"User_AutoLogin_Request")]
  internal partial class User_AutoLogin_Request : global::ProtoBuf.IExtensible
  {
    internal User_AutoLogin_Request() {}
    
    private string _app_key;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"app_key", DataFormat = global::ProtoBuf.DataFormat.Default)]
    internal string app_key
    {
      get { return _app_key; }
      set { _app_key = value; }
    }
    private int _app_login_type;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"app_login_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    internal int app_login_type
    {
      get { return _app_login_type; }
      set { _app_login_type = value; }
    }
    private string _unique_identifier;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"unique_identifier", DataFormat = global::ProtoBuf.DataFormat.Default)]
    internal string unique_identifier
    {
      get { return _unique_identifier; }
      set { _unique_identifier = value; }
    }
    private string _app_guest_access_token;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"app_guest_access_token", DataFormat = global::ProtoBuf.DataFormat.Default)]
    internal string app_guest_access_token
    {
      get { return _app_guest_access_token; }
      set { _app_guest_access_token = value; }
    }
    private string _app_facebook_access_token;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"app_facebook_access_token", DataFormat = global::ProtoBuf.DataFormat.Default)]
    internal string app_facebook_access_token
    {
      get { return _app_facebook_access_token; }
      set { _app_facebook_access_token = value; }
    }
    private ulong _app_player_id;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"app_player_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    internal ulong app_player_id
    {
      get { return _app_player_id; }
      set { _app_player_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"User_AutoLogin_Response")]
  internal partial class User_AutoLogin_Response : global::ProtoBuf.IExtensible
  {
    internal User_AutoLogin_Response() {}
    
    private ulong _player_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"player_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    internal ulong player_id
    {
      get { return _player_id; }
      set { _player_id = value; }
    }
    private string _token;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"token", DataFormat = global::ProtoBuf.DataFormat.Default)]
    internal string token
    {
      get { return _token; }
      set { _token = value; }
    }
    private int _login_type;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"login_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    internal int login_type
    {
      get { return _login_type; }
      set { _login_type = value; }
    }
    private string _ip;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"ip", DataFormat = global::ProtoBuf.DataFormat.Default)]
    internal string ip
    {
      get { return _ip; }
      set { _ip = value; }
    }
    private int _port;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"port", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    internal int port
    {
      get { return _port; }
      set { _port = value; }
    }
    private string _name;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    internal string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private string _avatar;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"avatar", DataFormat = global::ProtoBuf.DataFormat.Default)]
    internal string avatar
    {
      get { return _avatar; }
      set { _avatar = value; }
    }
    private string _country_code;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"country_code", DataFormat = global::ProtoBuf.DataFormat.Default)]
    internal string country_code
    {
      get { return _country_code; }
      set { _country_code = value; }
    }
    private string _secret_key;
    [global::ProtoBuf.ProtoMember(9, IsRequired = true, Name=@"secret_key", DataFormat = global::ProtoBuf.DataFormat.Default)]
    internal string secret_key
    {
      get { return _secret_key; }
      set { _secret_key = value; }
    }
    private double _server_time = default(double);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"server_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(double))]
    internal double server_time
    {
      get { return _server_time; }
      set { _server_time = value; }
    }
    private bool _is_country_code_changeable = default(bool);
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"is_country_code_changeable", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    internal bool is_country_code_changeable
    {
      get { return _is_country_code_changeable; }
      set { _is_country_code_changeable = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"User_LoginOrRegister_Request")]
  internal partial class User_LoginOrRegister_Request : global::ProtoBuf.IExtensible
  {
    internal User_LoginOrRegister_Request() {}
    
    private string _app_key;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"app_key", DataFormat = global::ProtoBuf.DataFormat.Default)]
    internal string app_key
    {
      get { return _app_key; }
      set { _app_key = value; }
    }
    private int _proto_version;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"proto_version", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    internal int proto_version
    {
      get { return _proto_version; }
      set { _proto_version = value; }
    }
    private int _device_type;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"device_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    internal int device_type
    {
      get { return _device_type; }
      set { _device_type = value; }
    }
    private int _login_type;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"login_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    internal int login_type
    {
      get { return _login_type; }
      set { _login_type = value; }
    }
    private string _account = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"account", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    internal string account
    {
      get { return _account; }
      set { _account = value; }
    }
    private string _password = "";
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"password", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    internal string password
    {
      get { return _password; }
      set { _password = value; }
    }
    private string _unique_identifier = "";
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"unique_identifier", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    internal string unique_identifier
    {
      get { return _unique_identifier; }
      set { _unique_identifier = value; }
    }
    private string _app_facebook_access_token = "";
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"app_facebook_access_token", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    internal string app_facebook_access_token
    {
      get { return _app_facebook_access_token; }
      set { _app_facebook_access_token = value; }
    }
    private string _app_guest_access_token = "";
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"app_guest_access_token", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    internal string app_guest_access_token
    {
      get { return _app_guest_access_token; }
      set { _app_guest_access_token = value; }
    }
    private long _facebook_access_token_expires = default(long);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"facebook_access_token_expires", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    internal long facebook_access_token_expires
    {
      get { return _facebook_access_token_expires; }
      set { _facebook_access_token_expires = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"User_LoginOrRegister_Response")]
  internal partial class User_LoginOrRegister_Response : global::ProtoBuf.IExtensible
  {
    internal User_LoginOrRegister_Response() {}
    
    private ulong _player_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"player_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    internal ulong player_id
    {
      get { return _player_id; }
      set { _player_id = value; }
    }
    private string _token;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"token", DataFormat = global::ProtoBuf.DataFormat.Default)]
    internal string token
    {
      get { return _token; }
      set { _token = value; }
    }
    private int _login_type;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"login_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    internal int login_type
    {
      get { return _login_type; }
      set { _login_type = value; }
    }
    private string _ip;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"ip", DataFormat = global::ProtoBuf.DataFormat.Default)]
    internal string ip
    {
      get { return _ip; }
      set { _ip = value; }
    }
    private int _port;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"port", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    internal int port
    {
      get { return _port; }
      set { _port = value; }
    }
    private string _name;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    internal string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private string _avatar;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"avatar", DataFormat = global::ProtoBuf.DataFormat.Default)]
    internal string avatar
    {
      get { return _avatar; }
      set { _avatar = value; }
    }
    private string _country_code;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"country_code", DataFormat = global::ProtoBuf.DataFormat.Default)]
    internal string country_code
    {
      get { return _country_code; }
      set { _country_code = value; }
    }
    private string _secret_key;
    [global::ProtoBuf.ProtoMember(9, IsRequired = true, Name=@"secret_key", DataFormat = global::ProtoBuf.DataFormat.Default)]
    internal string secret_key
    {
      get { return _secret_key; }
      set { _secret_key = value; }
    }
    private string _app_guest_access_token;
    [global::ProtoBuf.ProtoMember(10, IsRequired = true, Name=@"app_guest_access_token", DataFormat = global::ProtoBuf.DataFormat.Default)]
    internal string app_guest_access_token
    {
      get { return _app_guest_access_token; }
      set { _app_guest_access_token = value; }
    }
    private readonly global::System.Collections.Generic.List<string> _clear_keys = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(11, Name=@"clear_keys", DataFormat = global::ProtoBuf.DataFormat.Default)]
    internal global::System.Collections.Generic.List<string> clear_keys
    {
      get { return _clear_keys; }
    }
  
    private double _server_time = default(double);
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"server_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(double))]
    internal double server_time
    {
      get { return _server_time; }
      set { _server_time = value; }
    }
    private bool _is_country_code_changeable = default(bool);
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"is_country_code_changeable", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    internal bool is_country_code_changeable
    {
      get { return _is_country_code_changeable; }
      set { _is_country_code_changeable = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"User_UpdateInfo_Request")]
  internal partial class User_UpdateInfo_Request : global::ProtoBuf.IExtensible
  {
    internal User_UpdateInfo_Request() {}
    
    private string _country_code = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"country_code", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    internal string country_code
    {
      get { return _country_code; }
      set { _country_code = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"User_UpdateInfo_Response")]
  internal partial class User_UpdateInfo_Response : global::ProtoBuf.IExtensible
  {
    internal User_UpdateInfo_Response() {}
    
    private string _country_code = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"country_code", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    internal string country_code
    {
      get { return _country_code; }
      set { _country_code = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Leaderboard_Memberinfo")]
  internal partial class Leaderboard_Memberinfo : global::ProtoBuf.IExtensible
  {
    internal Leaderboard_Memberinfo() {}
    
    private ulong _player_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"player_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    internal ulong player_id
    {
      get { return _player_id; }
      set { _player_id = value; }
    }
    private string _name;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    internal string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private string _avatar;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"avatar", DataFormat = global::ProtoBuf.DataFormat.Default)]
    internal string avatar
    {
      get { return _avatar; }
      set { _avatar = value; }
    }
    private int _score;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"score", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    internal int score
    {
      get { return _score; }
      set { _score = value; }
    }
    private string _country_code;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"country_code", DataFormat = global::ProtoBuf.DataFormat.Default)]
    internal string country_code
    {
      get { return _country_code; }
      set { _country_code = value; }
    }
    private int _level;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    internal int level
    {
      get { return _level; }
      set { _level = value; }
    }
    private int _win_times;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"win_times", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    internal int win_times
    {
      get { return _win_times; }
      set { _win_times = value; }
    }
    private int _lose_times;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"lose_times", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    internal int lose_times
    {
      get { return _lose_times; }
      set { _lose_times = value; }
    }
    private uint _order;
    [global::ProtoBuf.ProtoMember(9, IsRequired = true, Name=@"order", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    internal uint order
    {
      get { return _order; }
      set { _order = value; }
    }
    private string _player_info_access_token = "";
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"player_info_access_token", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    internal string player_info_access_token
    {
      get { return _player_info_access_token; }
      set { _player_info_access_token = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Leaderboard_Meta")]
  internal partial class Leaderboard_Meta : global::ProtoBuf.IExtensible
  {
    internal Leaderboard_Meta() {}
    
    private string _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    internal string id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _spatial_dimension;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"spatial_dimension", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    internal int spatial_dimension
    {
      get { return _spatial_dimension; }
      set { _spatial_dimension = value; }
    }
    private int _time_dimension;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"time_dimension", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    internal int time_dimension
    {
      get { return _time_dimension; }
      set { _time_dimension = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Leaderboard_GetList_Request")]
  internal partial class Leaderboard_GetList_Request : global::ProtoBuf.IExtensible
  {
    internal Leaderboard_GetList_Request() {}
    
    private PVPProtobuf_Token.Leaderboard_Meta _meta;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"meta", DataFormat = global::ProtoBuf.DataFormat.Default)]
    internal PVPProtobuf_Token.Leaderboard_Meta meta
    {
      get { return _meta; }
      set { _meta = value; }
    }
    private int _offset = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"offset", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    internal int offset
    {
      get { return _offset; }
      set { _offset = value; }
    }
    private int _length = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"length", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    internal int length
    {
      get { return _length; }
      set { _length = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Leaderboard_GetList_Response")]
  internal partial class Leaderboard_GetList_Response : global::ProtoBuf.IExtensible
  {
    internal Leaderboard_GetList_Response() {}
    
    private PVPProtobuf_Token.Leaderboard_Meta _meta;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"meta", DataFormat = global::ProtoBuf.DataFormat.Default)]
    internal PVPProtobuf_Token.Leaderboard_Meta meta
    {
      get { return _meta; }
      set { _meta = value; }
    }
    private readonly global::System.Collections.Generic.List<PVPProtobuf_Token.Leaderboard_Memberinfo> _member_infos = new global::System.Collections.Generic.List<PVPProtobuf_Token.Leaderboard_Memberinfo>();
    [global::ProtoBuf.ProtoMember(2, Name=@"member_infos", DataFormat = global::ProtoBuf.DataFormat.Default)]
    internal global::System.Collections.Generic.List<PVPProtobuf_Token.Leaderboard_Memberinfo> member_infos
    {
      get { return _member_infos; }
    }
  
    private int _remaining_time = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"remaining_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    internal int remaining_time
    {
      get { return _remaining_time; }
      set { _remaining_time = value; }
    }
    private int _offset = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"offset", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    internal int offset
    {
      get { return _offset; }
      set { _offset = value; }
    }
    private int _next_offset = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"next_offset", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    internal int next_offset
    {
      get { return _next_offset; }
      set { _next_offset = value; }
    }
    private int _league_id = (int)-1;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"league_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)-1)]
    internal int league_id
    {
      get { return _league_id; }
      set { _league_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Leaderboard_SubmitScore_Request")]
  internal partial class Leaderboard_SubmitScore_Request : global::ProtoBuf.IExtensible
  {
    internal Leaderboard_SubmitScore_Request() {}
    
    private string _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    internal string id
    {
      get { return _id; }
      set { _id = value; }
    }
    private uint _score;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"score", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    internal uint score
    {
      get { return _score; }
      set { _score = value; }
    }
    private int _type;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    internal int type
    {
      get { return _type; }
      set { _type = value; }
    }
    private int _submit_mark;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"submit_mark", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    internal int submit_mark
    {
      get { return _submit_mark; }
      set { _submit_mark = value; }
    }
    private int _league_id = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"league_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    internal int league_id
    {
      get { return _league_id; }
      set { _league_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Social_Friend")]
  internal partial class Social_Friend : global::ProtoBuf.IExtensible
  {
    internal Social_Friend() {}
    
    private ulong _player_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"player_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    internal ulong player_id
    {
      get { return _player_id; }
      set { _player_id = value; }
    }
    private string _facebook_uid;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"facebook_uid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    internal string facebook_uid
    {
      get { return _facebook_uid; }
      set { _facebook_uid = value; }
    }
    private string _name;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    internal string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private string _avatar;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"avatar", DataFormat = global::ProtoBuf.DataFormat.Default)]
    internal string avatar
    {
      get { return _avatar; }
      set { _avatar = value; }
    }
    private int _source_from;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"source_from", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    internal int source_from
    {
      get { return _source_from; }
      set { _source_from = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Social_Facebook_Invitable_Friend")]
  internal partial class Social_Facebook_Invitable_Friend : global::ProtoBuf.IExtensible
  {
    internal Social_Facebook_Invitable_Friend() {}
    
    private string _facebook_uid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"facebook_uid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    internal string facebook_uid
    {
      get { return _facebook_uid; }
      set { _facebook_uid = value; }
    }
    private string _name;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    internal string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Social_GetFriendList_Request")]
  internal partial class Social_GetFriendList_Request : global::ProtoBuf.IExtensible
  {
    internal Social_GetFriendList_Request() {}
    
    private int _ext = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"ext", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    internal int ext
    {
      get { return _ext; }
      set { _ext = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Social_GetFriendList_Response")]
  internal partial class Social_GetFriendList_Response : global::ProtoBuf.IExtensible
  {
    internal Social_GetFriendList_Response() {}
    
    private readonly global::System.Collections.Generic.List<PVPProtobuf_Token.Social_Friend> _friends = new global::System.Collections.Generic.List<PVPProtobuf_Token.Social_Friend>();
    [global::ProtoBuf.ProtoMember(1, Name=@"friends", DataFormat = global::ProtoBuf.DataFormat.Default)]
    internal global::System.Collections.Generic.List<PVPProtobuf_Token.Social_Friend> friends
    {
      get { return _friends; }
    }
  
    private readonly global::System.Collections.Generic.List<PVPProtobuf_Token.Social_Facebook_Invitable_Friend> _facebook_invitable_friends = new global::System.Collections.Generic.List<PVPProtobuf_Token.Social_Facebook_Invitable_Friend>();
    [global::ProtoBuf.ProtoMember(2, Name=@"facebook_invitable_friends", DataFormat = global::ProtoBuf.DataFormat.Default)]
    internal global::System.Collections.Generic.List<PVPProtobuf_Token.Social_Facebook_Invitable_Friend> facebook_invitable_friends
    {
      get { return _facebook_invitable_friends; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Social_Stranger")]
  internal partial class Social_Stranger : global::ProtoBuf.IExtensible
  {
    internal Social_Stranger() {}
    
    private ulong _player_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"player_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    internal ulong player_id
    {
      get { return _player_id; }
      set { _player_id = value; }
    }
    private string _name;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    internal string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private string _avatar;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"avatar", DataFormat = global::ProtoBuf.DataFormat.Default)]
    internal string avatar
    {
      get { return _avatar; }
      set { _avatar = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Social_SearchStranger_Request")]
  internal partial class Social_SearchStranger_Request : global::ProtoBuf.IExtensible
  {
    internal Social_SearchStranger_Request() {}
    
    private string _search_str;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"search_str", DataFormat = global::ProtoBuf.DataFormat.Default)]
    internal string search_str
    {
      get { return _search_str; }
      set { _search_str = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Social_SearchStranger_Response")]
  internal partial class Social_SearchStranger_Response : global::ProtoBuf.IExtensible
  {
    internal Social_SearchStranger_Response() {}
    
    private readonly global::System.Collections.Generic.List<PVPProtobuf_Token.Social_Stranger> _strangers = new global::System.Collections.Generic.List<PVPProtobuf_Token.Social_Stranger>();
    [global::ProtoBuf.ProtoMember(1, Name=@"strangers", DataFormat = global::ProtoBuf.DataFormat.Default)]
    internal global::System.Collections.Generic.List<PVPProtobuf_Token.Social_Stranger> strangers
    {
      get { return _strangers; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Pair")]
  internal partial class Pair : global::ProtoBuf.IExtensible
  {
    internal Pair() {}
    
    private string _key;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"key", DataFormat = global::ProtoBuf.DataFormat.Default)]
    internal string key
    {
      get { return _key; }
      set { _key = value; }
    }
    private byte[] _value;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"value", DataFormat = global::ProtoBuf.DataFormat.Default)]
    internal byte[] value
    {
      get { return _value; }
      set { _value = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AppPlayerInfo")]
  internal partial class AppPlayerInfo : global::ProtoBuf.IExtensible
  {
    internal AppPlayerInfo() {}
    
    private ulong _player_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"player_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    internal ulong player_id
    {
      get { return _player_id; }
      set { _player_id = value; }
    }
    private string _name;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    internal string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private string _avatar;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"avatar", DataFormat = global::ProtoBuf.DataFormat.Default)]
    internal string avatar
    {
      get { return _avatar; }
      set { _avatar = value; }
    }
    private int _level;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    internal int level
    {
      get { return _level; }
      set { _level = value; }
    }
    private int _score;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"score", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    internal int score
    {
      get { return _score; }
      set { _score = value; }
    }
    private int _win_times;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"win_times", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    internal int win_times
    {
      get { return _win_times; }
      set { _win_times = value; }
    }
    private int _lose_times;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"lose_times", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    internal int lose_times
    {
      get { return _lose_times; }
      set { _lose_times = value; }
    }
    private uint _number;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"number", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    internal uint number
    {
      get { return _number; }
      set { _number = value; }
    }
    private uint _custom_data_number;
    [global::ProtoBuf.ProtoMember(9, IsRequired = true, Name=@"custom_data_number", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    internal uint custom_data_number
    {
      get { return _custom_data_number; }
      set { _custom_data_number = value; }
    }
    private readonly global::System.Collections.Generic.List<PVPProtobuf_Token.Pair> _custom_data = new global::System.Collections.Generic.List<PVPProtobuf_Token.Pair>();
    [global::ProtoBuf.ProtoMember(10, Name=@"custom_data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    internal global::System.Collections.Generic.List<PVPProtobuf_Token.Pair> custom_data
    {
      get { return _custom_data; }
    }
  
    private string _country_code;
    [global::ProtoBuf.ProtoMember(11, IsRequired = true, Name=@"country_code", DataFormat = global::ProtoBuf.DataFormat.Default)]
    internal string country_code
    {
      get { return _country_code; }
      set { _country_code = value; }
    }
    private uint _app_login_type;
    [global::ProtoBuf.ProtoMember(12, IsRequired = true, Name=@"app_login_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    internal uint app_login_type
    {
      get { return _app_login_type; }
      set { _app_login_type = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Social_GetAppInfo_Request")]
  internal partial class Social_GetAppInfo_Request : global::ProtoBuf.IExtensible
  {
    internal Social_GetAppInfo_Request() {}
    
    private string _player_info_access_token;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"player_info_access_token", DataFormat = global::ProtoBuf.DataFormat.Default)]
    internal string player_info_access_token
    {
      get { return _player_info_access_token; }
      set { _player_info_access_token = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Social_GetAppInfo_Response")]
  internal partial class Social_GetAppInfo_Response : global::ProtoBuf.IExtensible
  {
    internal Social_GetAppInfo_Response() {}
    
    private PVPProtobuf_Token.AppPlayerInfo _app_player_infos;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"app_player_infos", DataFormat = global::ProtoBuf.DataFormat.Default)]
    internal PVPProtobuf_Token.AppPlayerInfo app_player_infos
    {
      get { return _app_player_infos; }
      set { _app_player_infos = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Payment_CheckGooglePlayBilling_Request")]
  internal partial class Payment_CheckGooglePlayBilling_Request : global::ProtoBuf.IExtensible
  {
    internal Payment_CheckGooglePlayBilling_Request() {}
    
    private string _app_key;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"app_key", DataFormat = global::ProtoBuf.DataFormat.Default)]
    internal string app_key
    {
      get { return _app_key; }
      set { _app_key = value; }
    }
    private string _inapp_purchase_data;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"inapp_purchase_data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    internal string inapp_purchase_data
    {
      get { return _inapp_purchase_data; }
      set { _inapp_purchase_data = value; }
    }
    private string _inapp_data_signature;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"inapp_data_signature", DataFormat = global::ProtoBuf.DataFormat.Default)]
    internal string inapp_data_signature
    {
      get { return _inapp_data_signature; }
      set { _inapp_data_signature = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Payment_CheckGooglePlayBilling_Response")]
  internal partial class Payment_CheckGooglePlayBilling_Response : global::ProtoBuf.IExtensible
  {
    internal Payment_CheckGooglePlayBilling_Response() {}
    
    private string _inapp_purchase_data;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"inapp_purchase_data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    internal string inapp_purchase_data
    {
      get { return _inapp_purchase_data; }
      set { _inapp_purchase_data = value; }
    }
    private uint _is_verified;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"is_verified", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    internal uint is_verified
    {
      get { return _is_verified; }
      set { _is_verified = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
